services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: data_code
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5438:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - dcode
  app:
    container_name: dcode
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/backend
    ports:
      - "9992:8000"
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - dcode

networks:
  dcode:
    driver: bridge

volumes:
  db_data:
  superset_home:
