services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: data_code
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5438:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - dcode

networks:
  dcode:
    driver: bridge

volumes:
  db_data:
  superset_home:
